# Meeq-test-cfn-batch
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Bach settings

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:
  PJPrefix:
    Description: "Prefix for item name"
    Type: String
    Default: Meeq-test
  PJEnv:
    Description: "Enviroment"
    Type: String
    Default: Test

  ParamServiceRole:
    Description: "The IAM Role for batch service"
    Type: String
    Default: "arn:aws:iam::500877970798:role/service-role/AWSBatchServiceRole"
  ParamInstanceRole:
    Description: "IAM Role for the compute resources instance"
    Type: String
    Default: "ecsInstanceRole"
  ParamImageEltres:
    Description: "Amazon Machine Image (AMI) ID"
    Type: String
    Default: 500877970798.dkr.ecr.ap-northeast-1.amazonaws.com/meeq-dev-ecr:batch-eltres
  ParamImageCommon:
    Description: "Amazon Machine Image (AMI) ID"
    Type: String
    Default: 500877970798.dkr.ecr.ap-northeast-1.amazonaws.com/meeq-dev-ecr:batch-common
  ParamImageSim:
    Description: "Amazon Machine Image (AMI) ID"
    Type: String
    Default: 500877970798.dkr.ecr.ap-northeast-1.amazonaws.com/meeq-dev-ecr:batch-sim
  ParamSubnetId1:
    Description: "The subnet of the Amazon VPC"
    Type: String
    Default: subnet-0b3c78d6a44362e12
  ParamSubnetId2:
    Description: "The subnet of the Amazon VPC"
    Type: String
    Default: subnet-00434e4629a2736b8
  ParamSecurityGroupId:
    Description: "The Id of the Security Group"
    Type: String
    Default: sg-05cc7c71e34fc3fa1

# ------------------------------------------------------------#
# Resources
# ------------------------------------------------------------#
Resources:
  # ------------------------------------------------------------#
  # Create ComputeEnvironment
  # ------------------------------------------------------------#
  BatchServertest:
    Type: AWS::Batch::ComputeEnvironment
    Properties: 
      ComputeEnvironmentName: !Sub "${PJPrefix}-bat-srv-test01"
      Type: MANAGED
      State: ENABLED
      ServiceRole: !Ref ParamServiceRole
      ComputeResources:
        AllocationStrategy: BEST_FIT
        # BidPercentage: 50
        DesiredvCpus: 0

        # Ec2KeyPair:
        # ImageId: xxxx
        InstanceRole: !Ref ParamInstanceRole
        InstanceTypes:
        - optimal
        MaxvCpus: 24
        MinvCpus: 0
        # PlacementGroup: 
        SecurityGroupIds:
        - !Ref ParamSecurityGroupId
        # SpotIamFleetRole:
        Subnets:
        - !Ref ParamSubnetId1
        - !Ref ParamSubnetId2
        Type: EC2
  
  # ------------------------------------------------------------#
  # Create LaunchTemplates
  # ------------------------------------------------------------#

  # ------------------------------------------------------------#
  # Create JobQueue
  # ------------------------------------------------------------#
  BatchJobQueueCommon:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Sub "${PJPrefix}-bat-queue-test"
      Priority: 1
      State: ENABLED
      ComputeEnvironmentOrder:
      - ComputeEnvironment: !Ref BatchServertest
        Order: 1
  

  # ------------------------------------------------------------#
  # Create JobDefinition
  # ------------------------------------------------------------#
  BatchJobDefinitionC01:
    Type: AWS::Batch::JobDefinition
    Properties: 
      JobDefinitionName: !Sub "${PJPrefix}-bat-def-test01"
      Type: container
      ContainerProperties:
        Image: busybox01
        Memory: 512
        Privileged: false
        ReadonlyRootFilesystem: false
        User: "root"
        Vcpus: 1
      # NodeProperties:
      #   MainNode: 1
      #   NumNodes: 1
      #   NodeRangeProperties:
      #   - TargetNodes: "0:1"
      #     Container:
      #       ContainerProperties
      # Parameters: Json
      # RetryStrategy:
      #   Attempts: 1
      # Timeout:
      #   # The time duration in seconds (measured from the job attempt's startedAt timestamp)
      #   # after which AWS Batch terminates your jobs if they have not finished
      #   # Unit: Seconds
      #   AttemptDurationSeconds: 300
